name: shell commands
on:       # below push is the "event" 
  - workflow_dispatch                #push                 # if we change push to workflow_dispatch it means that we want to run it manually  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }} 
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 


jobs:
  terraform-workflow: # the job here is to give permissions to semantic tobe able to write the tags
    permissions:       # the job here is to give permissions to semantic tobe able to write the tags
      contents: write   # modify content
      issues: write      # modify issues
      pull-requests: write # modify pull request
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # clone a repository
      - name: Set Terraform
        uses: hashicorp/setup-terraform@v2  
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init  -force-copy # -force-copy flag is the cpoy our .tfstate into our s3 in aws 
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run:  terraform plan                         
      - name: release
        if:  github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev'        #github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}      # by default this token is already avialabel we don't need to creat it again 
      - name: Terraform apply
        if:  github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev'         #github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve
      #- name: Terraform destroy
       # run: terraform destroy -auto-approve     