name: shell commands
on:       # below push is the "event" 
  - push
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }} 
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 


jobs:
  terraform-workflow: # the job here is to give permissions to semantic tobe able to write the tags
    permissions:       # the job here is to give permissions to semantic tobe able to write the tags
      contents: write   # modify content
      issues: write      # modify issues
      pull-requests: write # modify pull request
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # clone a repository
      - name: Set Terraform
        uses: hashicorp/setup-terraform@v2  
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run:  terraform plan
      #- name: Terraform apply
        #run: terraform apply -auto-approve
      #- name: Terraform destroy
       # run: terraform destroy -auto-approve              
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}      # by default this token is already avialabel we don't need to creat it again 