name: shell commands
on:       # below push is the "event" 
  - push
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }} 
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run:  terraform plan
      #- name: Terraform apply
        #run: terraform apply -auto-approve
      #- name: Terraform destroy
       # run: terraform destroy -auto-approve              
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}      # by default this token is already avialabel we don't need to creat it again 